on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: setup
        run: yarn install
      - name: build
        run: yarn build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
